# Generated by Django 4.2.1 on 2023-06-02 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soLuong', models.PositiveIntegerField()),
                ('donGia', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DangNhap',
            fields=[
                ('id_DN', models.AutoField(primary_key=True, serialize=False)),
                ('tenDN', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('id_DV', models.AutoField(primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=30)),
                ('donGia', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id_HD', models.AutoField(primary_key=True, serialize=False)),
                ('donGiaPhong', models.FloatField()),
                ('tienDichVu', models.FloatField(default=0.0)),
                ('thue', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id_KH', models.AutoField(primary_key=True, serialize=False)),
                ('hoTen', models.CharField(max_length=50)),
                ('sdt', models.CharField(max_length=12)),
                ('diaChi', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('loaiKhach', models.CharField(choices=[('ND', 'Nội địa'), ('NG', 'Nước ngoài')], default='ND', max_length=2)),
                ('gioiTinh', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], default='M', max_length=1)),
                ('cccd', models.CharField(max_length=12)),
                ('quocTich', models.CharField(choices=[('VNM', 'Việt Nam'), ('USA', 'Hoa Kì'), ('JPN', 'Nhật Bản'), ('THA', 'Thái Lan'), ('CHN', 'Trung Quốc')], default='VNM', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiPhong',
            fields=[
                ('id_LP', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=30)),
                ('donGia', models.FloatField()),
                ('slNguoi', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='PhieuThuePhong',
            fields=[
                ('id_PHP', models.AutoField(primary_key=True, serialize=False)),
                ('ghiChu', models.CharField(max_length=200)),
                ('thoiGianBD', models.DateTimeField()),
                ('thoiGianKT', models.DateTimeField()),
                ('slNguoi', models.PositiveIntegerField(default=1)),
                ('trangThai', models.IntegerField(choices=[(0, 'Chưa thanh toán'), (1, 'Đã thanh toán')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('id_Phong', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('trangThai', models.IntegerField(choices=[(0, 'Trống'), (1, 'Đã thuê')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_User', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('chucVu', models.IntegerField(choices=[(1, 'Nhân viên'), (2, 'Quản lý'), (3, 'Admin')], default=1)),
                ('hoTen', models.CharField(max_length=50)),
                ('gioiTinh', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=1)),
                ('email', models.CharField(max_length=30)),
                ('sdt', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('hoTen__length__gt', 0)), name='USER_check_hoTen'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('gioiTinh__length', 0), _negated=True), name='USER_check_gioiTinh'),
        ),
        migrations.AddField(
            model_name='phong',
            name='id_LP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.loaiphong'),
        ),
        migrations.AddField(
            model_name='phieuthuephong',
            name='id_KH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.khachhang'),
        ),
        migrations.AddField(
            model_name='phieuthuephong',
            name='id_Phong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.phong'),
        ),
        migrations.AddConstraint(
            model_name='loaiphong',
            constraint=models.CheckConstraint(check=models.Q(('donGia__gt', 0)), name='LP_check_don_gia'),
        ),
        migrations.AddConstraint(
            model_name='loaiphong',
            constraint=models.CheckConstraint(check=models.Q(('slNguoi__gt', 0)), name='LP_check_so_luong_nguoi'),
        ),
        migrations.AddConstraint(
            model_name='khachhang',
            constraint=models.CheckConstraint(check=models.Q(('hoTen__length__gt', 0)), name='KH_hoTen_minlength'),
        ),
        migrations.AddConstraint(
            model_name='khachhang',
            constraint=models.CheckConstraint(check=models.Q(('sdt__length__gt', 10)), name='KH_sdt_minlength'),
        ),
        migrations.AddConstraint(
            model_name='khachhang',
            constraint=models.CheckConstraint(check=models.Q(('cccd__length__gt', 0)), name='KH_cccd_minlength'),
        ),
        migrations.AddConstraint(
            model_name='khachhang',
            constraint=models.CheckConstraint(check=models.Q(('quocTich__length__gt', 0)), name='KH_quocTich_minlength'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='id_NV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.user'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='id_PTP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phieuthuephong'),
        ),
        migrations.AddConstraint(
            model_name='dichvu',
            constraint=models.CheckConstraint(check=models.Q(('donGia__gte', 0)), name='DV_check_don_gia'),
        ),
        migrations.AddField(
            model_name='dangnhap',
            name='id_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='chitiethoadon',
            name='id_DV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dichvu'),
        ),
        migrations.AddField(
            model_name='chitiethoadon',
            name='id_HD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hoadon'),
        ),
        migrations.AddConstraint(
            model_name='phong',
            constraint=models.CheckConstraint(check=models.Q(('trangThai__range', (0, 1))), name='PHONG_check_trang_thai'),
        ),
        migrations.AddConstraint(
            model_name='phieuthuephong',
            constraint=models.CheckConstraint(check=models.Q(('trangThai__range', (0, 1))), name='PTP_check_trang_thai'),
        ),
        migrations.AddConstraint(
            model_name='phieuthuephong',
            constraint=models.CheckConstraint(check=models.Q(('thoiGianKT__gte', models.F('thoiGianBD'))), name='PTP_check_thoiGian'),
        ),
        migrations.AddConstraint(
            model_name='phieuthuephong',
            constraint=models.CheckConstraint(check=models.Q(('slNguoi__gte', 1)), name='PTP_check_so_luong_nguoi'),
        ),
        migrations.AddConstraint(
            model_name='hoadon',
            constraint=models.CheckConstraint(check=models.Q(('donGiaPhong__gte', 0)), name='HD_check_donGiaPhong'),
        ),
        migrations.AddConstraint(
            model_name='hoadon',
            constraint=models.CheckConstraint(check=models.Q(('tienDichVu__gte', 0)), name='HD_check_tienDichVu'),
        ),
        migrations.AddConstraint(
            model_name='dangnhap',
            constraint=models.CheckConstraint(check=models.Q(('tenDN__length__gt', 0)), name='DN_check_tenDN'),
        ),
        migrations.AddConstraint(
            model_name='dangnhap',
            constraint=models.CheckConstraint(check=models.Q(('password__length__gt', 0)), name='DN_check_password'),
        ),
        migrations.AddConstraint(
            model_name='chitiethoadon',
            constraint=models.CheckConstraint(check=models.Q(('donGia__gte', 0)), name='CTHD_check_don_gia'),
        ),
        migrations.AddConstraint(
            model_name='chitiethoadon',
            constraint=models.UniqueConstraint(fields=('id_HD', 'id_DV'), name='CTHD_unique_HD_DV'),
        ),
    ]
