# Generated by Django 4.2.1 on 2023-06-11 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phong',
            name='id_LP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loaiPhong', to='api.loaiphong'),
        ),
    ]
